In [9]:
import numpy as np
import pandas as pd
ao = np.loadtxt('/home/greyatom/monthly.ao.index.b50.current.ascii')
print (ao[:5])
dates = pd.date_range('1950-01','2017-03',freq = 'M')
print (dates)
print (" ")
AO = pd.Series(ao[:,2], index = dates)
print (AO)
print ("Value in November 2016")
print (AO['2016-11'])
print ("Value in 2016")
print (AO['2016'])
print (AO[AO>0])

[[  1.95000000e+03   1.00000000e+00  -6.03100000e-02]
 [  1.95000000e+03   2.00000000e+00   6.26810000e-01]
 [  1.95000000e+03   3.00000000e+00  -8.12750000e-03]
 [  1.95000000e+03   4.00000000e+00   5.55100000e-01]
 [  1.95000000e+03   5.00000000e+00   7.15770000e-02]]
DatetimeIndex(['1950-01-31', '1950-02-28', '1950-03-31', '1950-04-30',
               '1950-05-31', '1950-06-30', '1950-07-31', '1950-08-31',
               '1950-09-30', '1950-10-31',
               ...
               '2016-05-31', '2016-06-30', '2016-07-31', '2016-08-31',
               '2016-09-30', '2016-10-31', '2016-11-30', '2016-12-31',
               '2017-01-31', '2017-02-28'],
              dtype='datetime64[ns]', length=806, freq='M')
 
1950-01-31   -0.060310
1950-02-28    0.626810
1950-03-31   -0.008127
1950-04-30    0.555100
1950-05-31    0.071577
1950-06-30    0.538570
1950-07-31   -0.802480
1950-08-31   -0.851010
1950-09-30    0.357970
1950-10-31   -0.378900
1950-11-30   -0.515110
1950-12-31   -1.928100
1

In [10]:
import numpy as np
l1 = [1,2,3,4]
n1 = np.array(l1)
print (n1[n1>2])

[3 4]


In [16]:
import numpy as np
import pandas as pd
weather_data = pd.read_csv('/home/greyatom/weather_2012.csv')
print (weather_data['Dew Point Temp (C)'])
print (weather_data.head(5))
print (weather_data.info())
print (weather_data.dtypes)

0       -3.9
1       -3.7
2       -3.4
3       -3.2
4       -3.3
5       -3.3
6       -3.1
7       -3.6
8       -3.6
9       -3.1
10      -2.3
11      -2.1
12      -2.0
13      -1.7
14      -1.1
15      -0.4
16      -0.2
17       0.0
18       1.0
19       1.3
20       1.3
21       1.7
22       1.9
23       2.0
24       1.5
25       0.0
26      -0.9
27      -1.5
28      -2.3
29      -2.3
        ... 
8754   -16.0
8755   -16.5
8756   -16.5
8757   -16.5
8758   -16.3
8759   -15.1
8760   -14.4
8761   -14.0
8762   -13.4
8763   -14.4
8764   -12.8
8765   -12.4
8766   -11.7
8767   -11.3
8768   -10.3
8769    -9.6
8770    -8.9
8771    -7.9
8772    -7.5
8773    -6.6
8774    -5.7
8775    -4.6
8776    -4.0
8777    -3.3
8778    -3.1
8779    -2.7
8780    -2.4
8781    -1.5
8782    -1.8
8783    -2.1
Name: Dew Point Temp (C), Length: 8784, dtype: float64
             Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0  2012-01-01 00:00:00      -1.8                -3.9           86   
1  2012-01-01 

In [27]:
import pandas as pd
import numpy as np
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index=labels)
print df['name']
print df[df['attempts']>2]

a    Anastasia
b         Dima
c    Katherine
d        James
e        Emily
f      Michael
g      Matthew
h        Laura
i        Kevin
j        Jonas
Name: name, dtype: object
   attempts     name qualify  score
b         3     Dima      no    9.0
d         3    James      no    NaN
f         3  Michael     yes   20.0


In [31]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])

In [74]:
import numpy as np
print df
print ""
print df.loc[[('G1',3),('G2',2)],('A','B')]
print ""
d = df.loc[[('G1',3),('G2',2)],('A','B')]
mask = np.array([[True,False],[True,False]])
print d.values [mask]

             A         B
G1 1 -0.186348 -0.121318
   2  2.075913  0.154229
   3 -2.508215  0.710801
G2 1  0.726838 -0.041397
   2 -0.895237  1.229822
   3 -1.696919  0.047124

             A         B
G1 3 -2.508215  0.710801
G2 2 -0.895237  1.229822

[-2.50821508 -0.89523729]


In [2]:
import numpy as np
import pandas as pd
weather_data = pd.read_csv('/home/greyatom/weather_2012.csv')
#print (weather_data)
weather_description = weather_data['Weather']
weather_data[weather_data['Weather'].str.lower().str.contains('snow')]

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
41    2012-01-02 17:00:00      -2.1                -9.5           57   
44    2012-01-02 20:00:00      -5.6               -13.4           54   
45    2012-01-02 21:00:00      -5.8               -12.8           58   
47    2012-01-02 23:00:00      -7.4               -14.1           59   
48    2012-01-03 00:00:00      -9.0               -16.0           57   
50    2012-01-03 02:00:00     -10.5               -15.8           65   
51    2012-01-03 03:00:00     -11.3               -18.7           54   
53    2012-01-03 05:00:00     -12.9               -19.1           60   
54    2012-01-03 06:00:00     -13.3               -19.3           61   
55    2012-01-03 07:00:00     -14.0               -19.5           63   
84    2012-01-04 12:00:00     -13.7               -21.7           51   
86    2012-01-04 14:00:00     -11.3               -19.0           53   
87    2012-01-04 15:00:00     -10.2               -16.3           61   
88    2012-01-04 16:00:00      -9.4               -15.5           61   
89    2012-01-04 17:00:00      -8.9               -13.2           71   
90    2012-01-04 18:00:00      -8.9               -12.6           75   
91    2012-01-04 19:00:00      -8.4               -12.7           71   
92    2012-01-04 20:00:00      -7.8               -12.1           71   
93    2012-01-04 21:00:00      -7.6               -11.6           73   
94    2012-01-04 22:00:00      -9.5               -12.7           77   
95    2012-01-04 23:00:00      -9.6               -12.6           79   
96    2012-01-05 00:00:00      -8.8               -11.7           79   
97    2012-01-05 01:00:00      -7.5               -10.2           81   
98    2012-01-05 02:00:00      -5.4                -8.3           80   
99    2012-01-05 03:00:00      -5.0                -7.7           81   
100   2012-01-05 04:00:00      -4.1                -6.5           83   
101   2012-01-05 05:00:00      -7.0                -9.5           82   
102   2012-01-05 06:00:00      -8.2               -10.7           82   
103   2012-01-05 07:00:00      -7.1                -9.7           82   
104   2012-01-05 08:00:00      -6.1                -9.1           79   
...                   ...       ...                 ...          ...   
8730  2012-12-29 18:00:00      -9.3               -10.9           88   
8731  2012-12-29 19:00:00      -9.5               -11.2           87   
8732  2012-12-29 20:00:00      -9.7               -11.6           86   
8733  2012-12-29 21:00:00      -9.8               -11.8           85   
8734  2012-12-29 22:00:00     -10.1               -11.6           89   
8735  2012-12-29 23:00:00     -10.0               -12.0           85   
8736  2012-12-30 00:00:00      -9.6               -11.3           87   
8737  2012-12-30 01:00:00      -9.4               -10.5           92   
8738  2012-12-30 02:00:00      -9.3               -10.4           92   
8739  2012-12-30 03:00:00      -9.1               -10.4           90   
8740  2012-12-30 04:00:00      -9.3               -10.6           90   
8741  2012-12-30 05:00:00      -9.1               -10.4           90   
8742  2012-12-30 06:00:00      -9.3               -10.8           89   
8767  2012-12-31 07:00:00      -9.3               -11.3           85   
8768  2012-12-31 08:00:00      -8.6               -10.3           87   
8769  2012-12-31 09:00:00      -8.1                -9.6           89   
8770  2012-12-31 10:00:00      -7.4                -8.9           89   
8771  2012-12-31 11:00:00      -6.7                -7.9           91   
8772  2012-12-31 12:00:00      -5.8                -7.5           88   
8773  2012-12-31 13:00:00      -4.6                -6.6           86   
8774  2012-12-31 14:00:00      -3.4                -5.7           84   
8775  2012-12-31 15:00:00      -2.3                -4.6           84   
8776  2012-12-31 16:00:00      -1.4                -4.0           82   
8777  2012-12-31 17:00:00      -1.1                -3.3 

In [110]:
s = pd.Series(['a','b','c'])
print type(s)
s1 = s.str.lower().str.contains('a')
s2 = s.str.lower().__contains__('a')
print type(s1)
print dir(s1)
print (s1)
print (s2)

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
['T', '_AXIS_ALIASES', '_AXIS_IALIASES', '_AXIS_LEN', '_AXIS_NAMES', '_AXIS_NUMBERS', '_AXIS_ORDERS', '_AXIS_REVERSED', '_AXIS_SLICEMAP', '__abs__', '__add__', '__and__', '__array__', '__array_prepare__', '__array_priority__', '__array_wrap__', '__bool__', '__bytes__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__idiv__', '__imul__', '__init__', '__int__', '__invert__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__le__', '__len__', '__long__', '__lt__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__reduce__', '__reduce_ex__', '__rep

In [5]:
def times2 (x):
    return x*2
visibility_sum = weather_data['Visibility (km)'].apply(times2)
visibility_sum1 = weather_data['Weather'].apply(times2)
print visibility_sum
print visibility_sum1

0       16.0
1       16.0
2        8.0
3        8.0
4        9.6
5       12.8
6       12.8
7       16.0
8       16.0
9        8.0
10       2.4
11       8.0
12       9.6
13       9.6
14       9.6
15      12.8
16      25.8
17      32.2
18      25.8
19      25.8
20      50.0
21      50.0
22      38.6
23      50.0
24      50.0
25      50.0
26      50.0
27      50.0
28      50.0
29      50.0
        ... 
8754    50.0
8755    50.0
8756    50.0
8757    50.0
8758    50.0
8759    50.0
8760    50.0
8761    50.0
8762    50.0
8763    50.0
8764    50.0
8765    50.0
8766    50.0
8767    38.6
8768     6.4
8769     4.8
8770    12.8
8771    19.4
8772    25.8
8773    25.8
8774    22.6
8775    19.4
8776    25.8
8777    19.4
8778    19.4
8779    19.4
8780    19.4
8781     9.6
8782    19.4
8783    22.6
Name: Visibility (km), Length: 8784, dtype: float64
0                                         FogFog
1                                         FogFog
2       Freezing Drizzle,FogFreezing Drizzle,Fog
3       

In [29]:
import numpy as np
import pandas as pd
weather_data = pd.read_csv('/home/greyatom/weather_2012.csv')
max_10_temp=weather_data['Temp (C)'].sort_values(ascending=False).head(10)
occurance_of_temp=weather_data['Temp (C)'].value_counts().head(10)
print max_10_temp.values
print occurance_of_temp


[ 33.   33.   32.9  32.8  32.7  32.6  32.5  32.5  32.5  32.5]
16.6    65
1.1     58
0.8     47
1.5     45
19.3    44
21.1    43
2.6     43
0.4     41
1.3     40
14.6    39
Name: Temp (C), dtype: int64


In [20]:
import numpy as np
import pandas as pd
df = pd.read_csv('/home/greyatom/titanic.csv')
df.isnull().any()
passenger_class = df['Pclass'].value_counts().index
df['Embarked'].isnull()
fares_by_class = {}
for current_class in passenger_class:
    is_current_class = df['Pclass'] == current_class
    current_class_rows = df[is_current_class]
    current_class_fares = current_class_rows['Fare']
    fares_by_class [current_class] = current_class_fares.mean()
    
fares_by_class

{1: 84.15468749999992, 2: 20.66218315217391, 3: 13.675550101832997}

In [23]:
df.isnull().any()
df['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [31]:
df[df['Embarked'].isnull()] = 'Q'

In [33]:
any(df['Embarked'].isnull())

False

In [39]:
fares_by_class = {}
embarked_class = df['Embarked'].value_counts().index
for current_class in passenger_class:
    for current_embarked in embarked_class: 
        is_current_class = df['Pclass'] == current_class & df['Embarked'] == embarked_class
        current_class_rows = df[is_current_class]
        current_class_fares = current_class_rows['Fare']
        fares_by_class[current_class, = current_class_fares.mean()

fares_by_class

TypeError: cannot compare a dtyped [object] array with a scalar of type [bool]

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null object
Survived       891 non-null object
Pclass         891 non-null object
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null object
SibSp          891 non-null object
Parch          891 non-null object
Ticket         891 non-null object
Fare           891 non-null object
Cabin          204 non-null object
Embarked       891 non-null object
dtypes: object(12)
memory usage: 83.6+ KB


In [48]:
import numpy as np
import pandas as pd
df = pd.read_csv('/home/greyatom/titanic.csv')
pivot1 = df.pivot_table(values='Fare',index=['Embarked','Pclass'])
print pivot1

                       Fare
Embarked Pclass            
C        1       104.718529
         2        25.358335
         3        11.214083
Q        1        90.000000
         2        12.350000
         3        11.183393
S        1        70.364862
         2        20.327439
         3        14.644083
