In [75]:
import re

re.findall("{cat|dog|rat|fox|camel}.*box$","a quick brown fox jumped over a lazy rat dog camel dog box")

['fox', 'rat', 'dog', 'dog']

SyntaxError: invalid syntax (<ipython-input-55-a6246bc34ee5>, line 1)

In [126]:

i = range(0,3)
print i

[0, 1, 2]


'1234'

In [127]:
t = 'AAABAA'
for index in range(0,len(t))

SyntaxError: invalid syntax (<ipython-input-127-df6175494364>, line 2)

In [138]:
s1 = 'ABCD'
result = ''
count = 1
result += s1[0]
for i in range(0,len(s1)-1):
    if s1[i] == s1[i+1]:
        count +=1
    elif count > 1:
        result += str(count)+s1[i+1]
        count = 1
    elif count == 1:
        result += s1[i+1]
if(count > 1):
    result += str(count)
    

print result

ABCD


In [152]:
s1 = 'aabcddd'
s2 = 'abbbbccde'
set1 = set(s1)
set2 = set(s2)
print type (str(map(str,(set1^set2))))

<type 'str'>


In [154]:
import numpy as np
t = ([8, 4, 6], [1, 2, 3])
y = np.array(t)
print y

[[8 4 6]
 [1 2 3]]


In [156]:
import numpy as np
l1 = [10,20,3]
t1 = np.array (l1)
print t1
print t1.dtype
print t1.shape

[10 20  3]
int64
(3,)


In [159]:
i1 = [ 1,  1,  1,  1,  1]

print i1.shape

AttributeError: 'list' object has no attribute 'shape'

In [189]:
import numpy as np
l1 = [[ 1,  1,  1,  1,  1],[ 1,  1,  1,  1,  1],[ 1,  1,  1,  1,  1],[ 1,  1,  1,  1,  1],[ 1,  1,  1,  1,  1]]
i1 = np.array(l1)
i2 = np.array(l1)
print i1
i1[1:4,1:4]=0
i2[1:4][1:4]=0
print i1
print i2

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]]


In [191]:
a = np.random.rand(4,3,3)
print a

[[[ 0.63464559  0.96374936  0.99331453]
  [ 0.12463414  0.00182426  0.88945696]
  [ 0.29131577  0.53059578  0.4412654 ]]

 [[ 0.59205043  0.96029171  0.8806379 ]
  [ 0.18778682  0.57824258  0.55359427]
  [ 0.63986625  0.91906413  0.52811535]]

 [[ 0.36284344  0.19725852  0.25024489]
  [ 0.31031838  0.65334792  0.43702903]
  [ 0.74524062  0.17954175  0.94594429]]

 [[ 0.13819335  0.48383528  0.75461103]
  [ 0.74036123  0.56023118  0.48878186]
  [ 0.30500206  0.50229746  0.98551102]]]


In [192]:
print a[1][1][1]

0.578242575683


In [193]:
print a[2][1][1]

0.65334791913


In [197]:
print a[1:3,1:3,1]

[[ 0.57824258  0.91906413]
 [ 0.65334792  0.17954175]]


In [195]:
print a[0][1][2]

0.889456956031


In [196]:
import numpy as np
a1 = [10, 20, 30]
a2 = [[40, 50, 60], [70, 80, 90]]
a3 = np.append(a1,a2)
print a3

[10 20 30 40 50 60 70 80 90]


In [198]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print arr[5]

IndexError: index 5 is out of bounds for axis 0 with size 3

In [205]:
def has_unique_chars(s1):
    print "".join((str(s) for s in set(s1)))
print has_unique_chars("bar")

arb
None


In [208]:
def has_unique_chars(s1):
    if s1 == None:
        return False
    l2 = sorted(set(s1), key=s1.index)
    return s1 == "".join(str(x) for x in l2)
print has_unique_chars("bar")

True


In [222]:
import itertools
d1 = {'one':['a','b'],'two':['c','d']}
def solution(dic):
    d2 = d1.values()
    print d2

solution(d1)

[['c', 'd'], ['a', 'b']]


In [225]:
import numpy
world_milk = numpy.genfromtxt("/home/greyatom/world_milk.csv",dtype="|S30",skip_header=1,delimiter=",")

In [226]:
import numpy
world_milk = numpy.genfromtxt("/home/greyatom/world_milk.csv",dtype="|S30",skip_header=1,delimiter=",")

In [227]:
import numpy
world_milk = numpy.genfromtxt("/home/greyatom/world_milk.csv",dtype="|S30",skip_header=1,delimiter=",")

In [228]:
import numpy
world_milk = numpy.genfromtxt("/home/greyatom/world_milk.csv",dtype="|S30",skip_header=1,delimiter=",")
print world_milk

[['1986' 'Western Pacific' 'Viet Nam' 'Cow Milk' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1986' 'Europe' 'Switzerland' 'Cow Milk' '1.62']
 ['1985' 'Western Pacific' 'Viet Nam' 'buffalo Milk' '0.6']
 ['1985' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Europe' 'Switzerland' 'Other' '1.0']
 ['1984' 'Western Pacific' 'Viet Nam' 'buffalo Milk' '0.8']
 ['1984' 'Americas' 'Uruguay' 'Other' '']
 ['1984' 'Europe' 'Switzerland' 'Other' '2.5']]


In [229]:
import numpy
world_milk = numpy.genfromtxt("/home/greyatom/world_milk.csv",dtype="|S30",skip_header=1,delimiter=",")
print world_milk

[['1986' 'Western Pacific' 'Viet Nam' 'Cow Milk' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1986' 'Europe' 'Switzerland' 'Cow Milk' '1.62']
 ['1985' 'Western Pacific' 'Viet Nam' 'buffalo Milk' '0.6']
 ['1985' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Europe' 'Switzerland' 'Other' '1.0']
 ['1984' 'Western Pacific' 'Viet Nam' 'buffalo Milk' '0.8']
 ['1984' 'Americas' 'Uruguay' 'Other' '']
 ['1984' 'Europe' 'Switzerland' 'Other' '2.5']]


In [234]:
import numpy
world_milk = numpy.genfromtxt("/home/greyatom/world_milk.csv",dtype="|S30",skip_header=1,delimiter=",")
print world_milk
milk_consumption = world_milk[:,4]
print milk_consumption
milk_consumption_float = milk_consumption.astype(float)
print milk_consumption_float

[['1986' 'Western Pacific' 'Viet Nam' 'Cow Milk' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1986' 'Europe' 'Switzerland' 'Cow Milk' '1.62']
 ['1985' 'Western Pacific' 'Viet Nam' 'buffalo Milk' '0.6']
 ['1985' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Europe' 'Switzerland' 'Other' '1.0']
 ['1984' 'Western Pacific' 'Viet Nam' 'buffalo Milk' '0.8']
 ['1984' 'Americas' 'Uruguay' 'Other' '']
 ['1984' 'Europe' 'Switzerland' 'Other' '2.5']]
['0' '0.5' '1.62' '0.6' '0.5' '1.0' '0.8' '' '2.5']


ValueError: could not convert string to float: 

In [236]:
import numpy
world_milk = numpy.genfromtxt("/home/greyatom/world_milk.csv",dtype="|S30",skip_header=1,delimiter=",")
print world_milk
milk_consumption = world_milk[:,4]
print milk_consumption
milk_consumption[7] = 0
milk_consumption_float = milk_consumption.astype(np.float64)
print milk_consumption_float

[['1986' 'Western Pacific' 'Viet Nam' 'Cow Milk' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1986' 'Europe' 'Switzerland' 'Cow Milk' '1.62']
 ['1985' 'Western Pacific' 'Viet Nam' 'buffalo Milk' '0.6']
 ['1985' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Europe' 'Switzerland' 'Other' '1.0']
 ['1984' 'Western Pacific' 'Viet Nam' 'buffalo Milk' '0.8']
 ['1984' 'Americas' 'Uruguay' 'Other' '']
 ['1984' 'Europe' 'Switzerland' 'Other' '2.5']]
['0' '0.5' '1.62' '0.6' '0.5' '1.0' '0.8' '' '2.5']
[ 0.    0.5   1.62  0.6   0.5   1.    0.8   0.    2.5 ]


In [ ]:
import numpy
world_milk = numpy.genfromtxt("/home/greyatom/world_milk.csv",dtype="|S30",skip_header=1,delimiter=",")
print world_milk
milk_consumption = world_milk[:,4]
print milk_consumption
milk_consumption_float = milk_consumption.astype(np.float64)
print milk_consumption_float